package org.redhelp.common.types;

public enum NotificationTypes {
    EVENT_NOTIFICATION,
    BLOOD_REQUEST_RECEIVED_NOTIFICATION,
    BLOOD_REQUEST_ACCEPTED_NOTIFICATION,
    BLOOD_PROFILE_ACCESS_NOTIFICATION,
    BLOOD_PROFILE_ACCEPTED_NOTIFICATION,
    NEW_EVENT_NOTIFICATION,
    MISC_NOTIFICATION
    
}
